base_model: codellama/CodeLlama-7b-Instruct-hf
base_model_config: codellama/CodeLlama-7b-Instruct-hf
model_type: LlamaForCausalLM
tokenizer_type: CodeLlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /work/06922/jiyang/maverick2/projects/etestgen/_work/setup/nestack2e-no-name-ft/train/train/train-nestack2e-no-name-ft.jsonl
    type:
      system_prompt: "You are a helpful programming assistant and an expert Java programmer. You are helping a user writing exceptional-behavior tests for their Java code."
      field_system: system
      system_format: "{system}"
      field_instruction: instruction
      field_input: input
      field_output: output
      format: "{instruction}"
      no_input_format: "{instruction}"


dataset_prepared_path:
val_set_size: 0.01
output_dir: /work/06922/jiyang/maverick2/projects/etestgen/_work/exp/nestack2e-no-name-ft/fft-codellama-7b/

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter:
lora_model_dir:
lora_r:
lora_alpha:
lora_dropout:
lora_target_linear:
lora_fan_in_fan_out:

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
eval_steps: 20
save_steps:
debug:
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
